import data from "./bangladesh-geo.json";
import type { DistrictId } from "./districts";

/** One district outline: an SVG path in map units, and an interior point for pins. */
export interface DistrictShape {
  d: string;
  c: [number, number];
}

/** District outlines, generated by scripts/build-bd-map.ts. Draw in a `0 0 width height` viewBox. */
export const BD_GEO = data as {
  width: number;
  height: number;
  districts: Record<DistrictId, DistrictShape>;
};

export const BD_GEO_CREDIT = {
  text: "Boundaries: BBS / OCHA via geoBoundaries, CC BY 3.0 IGO",
  href: "https://www.geoboundaries.org/",
};
