/**
 * Bangladesh's 64 districts and 8 divisions, with current official spellings.
 * Client-safe and small: the outlines live separately in bangladesh-geo.json
 * (generated by scripts/build-bd-map.ts) so forms that only validate ids
 * don't ship the shapes.
 */

export const DIVISIONS = [
  "Dhaka",
  "Chattogram",
  "Rajshahi",
  "Khulna",
  "Barishal",
  "Sylhet",
  "Rangpur",
  "Mymensingh",
] as const;

export type Division = (typeof DIVISIONS)[number];

export const DISTRICTS = [
  { id: "dhaka", name: "Dhaka", division: "Dhaka" },
  { id: "faridpur", name: "Faridpur", division: "Dhaka" },
  { id: "gazipur", name: "Gazipur", division: "Dhaka" },
  { id: "gopalganj", name: "Gopalganj", division: "Dhaka" },
  { id: "kishoreganj", name: "Kishoreganj", division: "Dhaka" },
  { id: "madaripur", name: "Madaripur", division: "Dhaka" },
  { id: "manikganj", name: "Manikganj", division: "Dhaka" },
  { id: "munshiganj", name: "Munshiganj", division: "Dhaka" },
  { id: "narayanganj", name: "Narayanganj", division: "Dhaka" },
  { id: "narsingdi", name: "Narsingdi", division: "Dhaka" },
  { id: "rajbari", name: "Rajbari", division: "Dhaka" },
  { id: "shariatpur", name: "Shariatpur", division: "Dhaka" },
  { id: "tangail", name: "Tangail", division: "Dhaka" },

  { id: "bandarban", name: "Bandarban", division: "Chattogram" },
  { id: "brahmanbaria", name: "Brahmanbaria", division: "Chattogram" },
  { id: "chandpur", name: "Chandpur", division: "Chattogram" },
  { id: "chattogram", name: "Chattogram", division: "Chattogram" },
  { id: "coxs-bazar", name: "Cox’s Bazar", division: "Chattogram" },
  { id: "cumilla", name: "Cumilla", division: "Chattogram" },
  { id: "feni", name: "Feni", division: "Chattogram" },
  { id: "khagrachhari", name: "Khagrachhari", division: "Chattogram" },
  { id: "lakshmipur", name: "Lakshmipur", division: "Chattogram" },
  { id: "noakhali", name: "Noakhali", division: "Chattogram" },
  { id: "rangamati", name: "Rangamati", division: "Chattogram" },

  { id: "bogura", name: "Bogura", division: "Rajshahi" },
  { id: "chapai-nawabganj", name: "Chapai Nawabganj", division: "Rajshahi" },
  { id: "joypurhat", name: "Joypurhat", division: "Rajshahi" },
  { id: "naogaon", name: "Naogaon", division: "Rajshahi" },
  { id: "natore", name: "Natore", division: "Rajshahi" },
  { id: "pabna", name: "Pabna", division: "Rajshahi" },
  { id: "rajshahi", name: "Rajshahi", division: "Rajshahi" },
  { id: "sirajganj", name: "Sirajganj", division: "Rajshahi" },

  { id: "bagerhat", name: "Bagerhat", division: "Khulna" },
  { id: "chuadanga", name: "Chuadanga", division: "Khulna" },
  { id: "jashore", name: "Jashore", division: "Khulna" },
  { id: "jhenaidah", name: "Jhenaidah", division: "Khulna" },
  { id: "khulna", name: "Khulna", division: "Khulna" },
  { id: "kushtia", name: "Kushtia", division: "Khulna" },
  { id: "magura", name: "Magura", division: "Khulna" },
  { id: "meherpur", name: "Meherpur", division: "Khulna" },
  { id: "narail", name: "Narail", division: "Khulna" },
  { id: "satkhira", name: "Satkhira", division: "Khulna" },

  { id: "barguna", name: "Barguna", division: "Barishal" },
  { id: "barishal", name: "Barishal", division: "Barishal" },
  { id: "bhola", name: "Bhola", division: "Barishal" },
  { id: "jhalokathi", name: "Jhalokathi", division: "Barishal" },
  { id: "patuakhali", name: "Patuakhali", division: "Barishal" },
  { id: "pirojpur", name: "Pirojpur", division: "Barishal" },

  { id: "habiganj", name: "Habiganj", division: "Sylhet" },
  { id: "moulvibazar", name: "Moulvibazar", division: "Sylhet" },
  { id: "sunamganj", name: "Sunamganj", division: "Sylhet" },
  { id: "sylhet", name: "Sylhet", division: "Sylhet" },

  { id: "dinajpur", name: "Dinajpur", division: "Rangpur" },
  { id: "gaibandha", name: "Gaibandha", division: "Rangpur" },
  { id: "kurigram", name: "Kurigram", division: "Rangpur" },
  { id: "lalmonirhat", name: "Lalmonirhat", division: "Rangpur" },
  { id: "nilphamari", name: "Nilphamari", division: "Rangpur" },
  { id: "panchagarh", name: "Panchagarh", division: "Rangpur" },
  { id: "rangpur", name: "Rangpur", division: "Rangpur" },
  { id: "thakurgaon", name: "Thakurgaon", division: "Rangpur" },

  { id: "jamalpur", name: "Jamalpur", division: "Mymensingh" },
  { id: "mymensingh", name: "Mymensingh", division: "Mymensingh" },
  { id: "netrokona", name: "Netrokona", division: "Mymensingh" },
  { id: "sherpur", name: "Sherpur", division: "Mymensingh" },
] as const satisfies readonly { id: string; name: string; division: Division }[];

export type District = (typeof DISTRICTS)[number];
export type DistrictId = District["id"];

export const DISTRICT_BY_ID = new Map<string, District>(DISTRICTS.map((d) => [d.id, d]));

export function isDistrictId(id: string): id is DistrictId {
  return DISTRICT_BY_ID.has(id);
}
